name: release

on:
  push:
    tags:
      - 'v*'        # e.g. v0.3.2

jobs:
  fw-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install ARM GCC (arm-none-eabi)
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '14.3.Rel1'

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi.cmake

      - name: Build
        shell: bash
        run: cmake --build build --config Release -j 8

      - name: Archive artifacts
        shell: bash
        run: |
          mkdir -p dist
          cp -r build/**/*.elf dist/ || true
          cp -r build/**/*.hex dist/ || true
          cp -r build/**/*.bin dist/ || true
          cp -r build/**/*.map dist/ || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: 
